// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoResizeController from "./auto_resize_controller"
application.register("auto-resize", AutoResizeController)

import DelayedSubmitController from "./delayed_submit_controller"
application.register("delayed-submit", DelayedSubmitController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SoundChangeController from "./sound_change_controller"
application.register("sound-change", SoundChangeController)

import SoundLinkController from "./sound_link_controller"
application.register("sound-link", SoundLinkController)

import SubmitSuccessController from "./submit_success_controller"
application.register("submit-success", SubmitSuccessController)

import WindowToggleController from "./window_toggle_controller"
application.register("window-toggle", WindowToggleController)
